#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/MarquiseRosier/learning.git"

strains:
  - name: default
    code: https://github.com/MarquiseRosier/learning.git#master
    content: https://github.com/MarquiseRosier/learning.git#master
    static: https://github.com/MarquiseRosier/learning.git/htdocs#master
    package: mrosier/a520352bd78340c7d51ee221a6bfd0ee6aa6dea9

  - name: v2
    code: https://github.com/MarquiseRosier/learning.git#master
    content: https://github.com/MarquiseRosier/learning.git#v2
    static: https://github.com/MarquiseRosier/learning.git/htdocs#master
    url: https://marquise.helix-demo.xyz/v2